scalar Date

type Query {
  users: [User]!
  user(id: ID!): User
  findUser(username: String!): User
}

type Mutation {
  authenticate(username: String!, password: String!): AuthReponse!

  addUser(mail: String!, username: String!, password: String!): StandardStatus!
  updateUser(id: ID!, mail: String, username: String, password: String,
             playedGames: Int, wonGames: Int, rating: Int): StandardStatus!
  deleteUser(id: ID!): StandardStatus!
}

type User {
  id: ID!
  mail: String!
  username: String!

  playedGames: Int!
  wonGames: Int!
  rating: Int!

  lastLogin: Date
}

interface Status {
  success: Boolean!
  message: String!
}

type StandardStatus implements Status {
  success: Boolean!
  message: String!
}

type AuthReponse implements Status {
  success: Boolean!
  message: String!
  user: User
}
